api_platform:
  title: 'Padel API'
  description: 'The internal Api for Padel app'
  version: 0.0.1
  show_webby: false
  formats:
    json:
      mime_types: ['application/json']
    jsonld:
      mime_types: ['application/ld+json']
    html:
      mime_types: ['text/html']